### ISSUE TITLE
Explicit @import?

### ISSUE THREAD

**Issue by strarsis** [sass-eyeglass/eyeglass#74]
The [eyeglass-inline-svg](https://github.com/strarsis/eyeglass-inline-svg) module @imports the [eyeglass-file-text](https://github.com/strarsis/eyeglass-file-text) module.
Now I get a Segmentation fault when @importing.
It seems that functions from eyeglass-exports.js are auto-imported/loaded without using @import, 
but not sass from sass/ directory of the module.
Is the Segmentation fault caused by recursive importing because of the behaviour described above?

What approach is the right one?
@import another eyeglass module when it is used in any way?
@import only for the sass files, not for exported functions?

I prepared a sample repository for this: https://github.com/strarsis/eyeglass_import_test
````
$ git clone https://github.com/strarsis/eyeglass_import_test.git
$ cd eyeglass_import_test
$ nvm use v4.0.0 # (for example)
$ npm install
$ npm install -g gulp-cli (if not already installed)
$ gulp
````
````
[16:30:50] Using gulpfile ~/eyeglass_import_test/Gulpfile.js
[16:30:50] Starting 'svg'...
[16:30:50] Finished 'svg' after 137 ms
[16:30:50] Starting 'sass'...
[16:30:50] Finished 'sass' after 17 ms
[16:30:50] Starting 'default'...
[16:30:50] Finished 'default' after 13 μs
Segmentation fault
````

Thank you and 
with best regards

**Comment by strarsis** [comment]
I debugged a bit and found out that it imports the same files over and over again in a loop.
How can I further diagnose this?

**Comment by chriseppstein** [comment]
Hi @strarsis,
I poked around. I found that in some cases you do not call the importer callback but instead raise an exception which will cause a segfault. I don't know if that is the cause. How did you determine that the same files are being imported over and over again?

I filed a bug for the error handling issue: https://github.com/strarsis/eyeglass-file-text/issues/1

I'll download the test case you made and see what I can find out.

**Comment by eoneill** [comment]
Firstly, javascript functions exposed via `eyeglass-exports.js` are indeed auto-loaded (e.g. they're loaded if the module is declared as an npm dependency). Sass `@functions`/`@mixins`/etc (anything in `.s[ac]ss` files) are not loaded until you do `@import` them.

This is by design and aligns with the way Ruby Sass extensions work.

Now, onto the issue... this looks like it's a known issue with `node-sass`. This should be fixed when `node-sass@3.4.2` is released. See https://github.com/sass/node-sass/pull/1220

I manually forced `node_modules/gulp-sass` to use `node-sass@3.3.3` and it compiles.

Also related: #73 #69

**Comment by chriseppstein** [comment]
@eoneill good catch. I was about 15 mintutes behind you :stuck_out_tongue_winking_eye:

**Comment by chriseppstein** [comment]
Closing as duplicate of #69.

**Comment by strarsis** [comment]
Also with the correctd error handling in eyeglass-file-text, I still get a Segmentation fault.
When I downgrade node-sass to 3.3.3 the Segmentation fault is fixed, so the Segmentation fault is caused by this node-sass bug, too.

With best regards
